language: python
python:
    - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

<<<<<<< HEAD
branches:
  only:
  - gh-pages
  - /.*/
=======
#branches:
#  only:
#    - master
>>>>>>> f910bf0ee46c1092894ad7a12eda7c46244d1a85
# command to run tests
script:
  - python travis.py # or py.test for Python versions 3.5 and below
