language: python
python:
    - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

branches:
  only:
    - release
# command to run tests
script:
  - python PoGoBot.py # or py.test for Python versions 3.5 and below
